# Generated by Django 4.0.3 on 2022-03-27 11:53

import django.core.validators
from django.db import migrations, models
import utils.avatar_utils


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=utils.avatar_utils.AvatarUtils.upload_to),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^\\+380[\\d]{9}$', 'Invalid phone number. Number must begin with +380 plus 9 digits')]),
        ),
    ]
