# Generated by Django 4.0.3 on 2022-03-16 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computermodel',
            options={'verbose_name': 'Computer'},
        ),
        migrations.AlterModelTable(
            name='computermodel',
            table='computers',
        ),
    ]
