# Generated by Django 4.0.3 on 2022-03-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_alter_computermodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computermodel',
            name='screen',
            field=models.FloatField(),
        ),
    ]
